/// Flutter icons MovieGenieIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MovieGenieIcons
///      fonts:
///       - asset: fonts/MovieGenieIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MovieGenieIcons {
  MovieGenieIcons._();

  static const _kFontFam = 'MovieGenieIcons';
  static const String? _kFontPkg = null;

  static const IconData films = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData main = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selections = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
